theme: jekyll-theme-minimal
logo: /assets/img/patrick_ux_jr.png
title: "Patrick A. Cadenas"
description: > 
Soy un diseñador UX Jr orientado a la creacion y mejora de productos digitales, me centro en la busqueda de 
soluciones que brinden coherencia, simplicidad y experiencias agradables.
<br><br>
He trabajado en proyectos Webs como Moviles, colaboro bien en equipo y soy solvente y emprendedor al momento de adoptar 
responsabilidades, trabajo orientado a resultados.
show_downloads: False
google_analytics:
